//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrencyConverter.Application.Tests.Repositories {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApiData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CurrencyConverter.Application.Tests.Repositories.ApiData", typeof(ApiData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;status&quot;: {
        ///        &quot;timestamp&quot;: &quot;2021-05-17T16:55:55.109Z&quot;,
        ///        &quot;error_code&quot;: 0,
        ///        &quot;error_message&quot;: null,
        ///        &quot;elapsed&quot;: 17,
        ///        &quot;credit_count&quot;: 1,
        ///        &quot;notice&quot;: null
        ///    },
        ///    &quot;data&quot;: {
        ///        &quot;BTC&quot;: {
        ///            &quot;id&quot;: 1,
        ///            &quot;name&quot;: &quot;Bitcoin&quot;,
        ///            &quot;symbol&quot;: &quot;BTC&quot;,
        ///            &quot;slug&quot;: &quot;bitcoin&quot;,
        ///            &quot;num_market_pairs&quot;: 9544,
        ///            &quot;date_added&quot;: &quot;2013-04-28T00:00:00.000Z&quot;,
        ///            &quot;tags&quot;: [ &quot;mineable&quot;, &quot;pow&quot;, &quot;sha-256&quot;, &quot;stor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Payload {
            get {
                return ResourceManager.GetString("Payload", resourceCulture);
            }
        }
    }
}
